Fix ACCESS_FINE_LOCATION error with Google Play services package
Error:
----------
     FATAL EXCEPTION: GoogleLocationService
     Process: com.google.android.gms.persistent
     java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
----------